name: build

on:
  workflow_dispatch:
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Get latest tag
      run: |
        set -x
        echo "TAG=$(git describe --abbrev=0)" >> $GITHUB_ENV

    - name: install prerequisites
      run: |
        echo "tag: $TAG"
        cargo install diceware
        command -v diceware

    - name: Run Build
      run: cargo b -r

    - name: Run Tests
      run: cargo t 
